### ISSUE TITLE
No Offline Notice

### ISSUE THREAD

**Issue by coffeepanda** [Trikolon/cfp-radio#8]
Unsuccessfully buffering stream does not result in "Stream Offline" notice

_Sent from my OnePlus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Trikolon** [comment]
Could you please provide a more specific error description. Please include the steps to reproduce the error and possibly your browser console log (F12).

**Comment by coffeepanda** [comment]
Force clearing Chrome app data and reloading the page resolved it. Only wanted to publish it straight away before I forget about it the next morning.
